filetype on
syntax on
colorscheme Tomorrow-Night

set colorcolumn=80
set number

filetype indent on
set nowrap
set tabstop=2
set shiftwidth=2
set expandtab
set smartindent
set autoindent

set nomodeline
set modelines=0
